export const localStorageKeys = [
  "accessToken",
  "refreshToken",
  "saved",
  "liked",
  "loaded",
  "following",
  "sortFollowingKey",
  "reversedFollowing",
  "sortPlaylistsKey",
  "reversedPlaylists",
  "sortTracksKey",
  "reversedTracks",
  "user",
];
