import Head from "next/head";
import styles from "@/styles/Playlist.module.css";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Track from "@/components/track";
import Image from "next/image";

export default function Home() {
  const [playlist, setPlaylist] = useState();
  const [tracks, setTracks] = useState();

  const [vertical, setVertical] = useState();

  const router = useRouter();

  function useToken(Function) {
    if (parseInt(localStorage.expiresAt) < new Date().getTime()) {
      fetch("https://accounts.spotify.com/api/token", {
        method: "POST",
        body: new URLSearchParams({
          refresh_token: localStorage.refreshToken,
          grant_type: "refresh_token",
        }).toString(),
        headers: {
          "Content-Type": "application/x-www-form-urlencoded",
          Authorization:
            "Basic ZWQxMjMyODcxMTMzNDVjNDkzMzhkMWNmMjBiZWM5MGU6NjE2Mzg1ZjJlYzNkNGQ2M2E3OWJkMWIxZGZhM2M4MGM=",
        },
      })
        .then((response) => response.json())
        .then((body) => {
          if (body.error) {
            return console.error(body.error_description);
          }

          localStorage.accessToken = body.access_token;
          localStorage.refreshToken = body.refresh_token;
          localStorage.expiresAt = (3000000 + new Date().getTime()).toString();

          Function(localStorage.accessToken);
        });
    } else {
      Function(localStorage.accessToken);
    }
  }

  function loadTracks({ tracks: { next, items } }, temp) {
    temp = [...temp, ...items];

    if (next) {
      fetch(next, {
        headers: {
          Authorization: "Bearer " + localStorage.accessToken,
        },
      })
        .then((response) => response.json())
        .then((body) => {
          loadTracks({ tracks: body }, temp);
        });
    } else {
      setTracks(temp);
    }
  }

  useEffect(() => {
    setVertical(innerHeight > innerWidth);

    onresize = (e) => {
      setVertical(innerHeight > innerWidth);
    };

    if (!localStorage.accessToken) router.replace("/");
    else {
      const { playlistId } = router.query;

      if (playlistId !== undefined) {
        useToken((accessToken) => {
          fetch("https://api.spotify.com/v1/playlists/" + playlistId, {
            headers: {
              Authorization: "Bearer " + accessToken,
            },
          })
            .then((response) => response.json())
            .then((body) => {
              setPlaylist({
                image: body?.images[0].url,
                name: body.name,
                owner: body.owner.display_name,
              });
              loadTracks(body, []);
            });
        });
      }
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>{playlist?.name || "Playlist"} - Spotify Helper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="header">
          <div className="left">
            <div
              className="button"
              onClick={() => {
                router.replace("/home");
              }}
            >
              <Image src="/back.svg" alt="back" width={40} height={40} />
            </div>
          </div>

          <div className="center">
            <div className="title">Spotify Helper</div>
          </div>
        </div>
        <div className={styles.body}>
          <div
            className={
              vertical
                ? `${styles.playlist} ${styles.vertical}`
                : styles.playlist
            }
          >
            {playlist && (
              <>
                <img
                  src={playlist.image}
                  alt={playlist.name + " image"}
                  className={styles.image}
                />
                <div>
                  <div className={styles.name}>{playlist.name}</div>
                  <div className={styles.owner}>
                    {playlist.owner}
                    <div className="button">
                      <Image src="/play.svg" width={40} height={40} />
                    </div>
                  </div>
                </div>
              </>
            )}
          </div>
          {tracks?.map((track, index) => (
            <Track
              track={track}
              id={track.id}
              index={index + 1}
              vertical={vertical}
            />
          ))}
        </div>
      </div>
    </>
  );
}
