import Head from "next/head";
import { useEffect } from "react";
import { useRouter } from "next/router";
import Image from "next/image";

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    if (localStorage.refreshToken) {
      router.replace("/home");
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>Spotify Helper 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="body">
          <a
            className="button"
            href={
              "https://accounts.spotify.com/authorize?" +
              new URLSearchParams({
                response_type: "code",
                client_id: "ed123287113345c49338d1cf20bec90e",
                scope: [
                  "user-read-playback-state",
                  "user-modify-playback-state",
                  "user-read-private",
                ].join(" "),
                redirect_uri: location.origin,
              }).toString()
            }
          >
            <Image src="/enter.svg" alt="enter" width={40} height={40} />
            <div>Enter with Spotify</div>
          </a>
        </div>
      </div>
    </>
  );
}
