import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useEffect } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    if (localStorage.refreshToken) {
      router.replace("/home");
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>NexTest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="body">
          <a
            className="button"
            href="https://accounts.spotify.com/authorize?response_type=code&client_id=ed123287113345c49338d1cf20bec90e&scope=user-read-playback-state+user-modify-playback-state+user-read-private&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fcallback"
          >
            <div className={styles.text}>Login with Spotify</div>
          </a>
        </div>
      </div>
    </>
  );
}
