import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Playlist from "@/components/playlist";
import Image from "next/image";
import getAccessToken from "@/functions/getAccessToken";

export default function Home() {
  const [playlists, setPlaylists] = useState();
  const router = useRouter();

  function loadPlaylists({ next, items }, temp) {
    temp = [...temp, ...items];

    if (next) {
      fetch(next, {
        headers: {
          Authorization: "Bearer " + localStorage.accessToken,
        },
      })
        .then((response) => response.json())
        .then((body) => {
          if (body.error) {
            console.error(body.error_description);
          } else {
            loadPlaylists(body, temp);
          }
        });
    } else {
      setPlaylists(temp);
    }
  }

  useEffect(() => {
    if (!localStorage.accessToken) router.replace("/");
    else {
      getAccessToken((accessToken) => {
        fetch("https://api.spotify.com/v1/me/playlists", {
          headers: {
            Authorization: "Bearer " + accessToken,
          },
        })
          .then((response) => response.json())
          .then((body) => {
            if (body.error) {
              console.error(body.error_description);
            } else {
              loadPlaylists(body, []);
            }
          });
      });
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>Página Inicial - Spotify Helper</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <div className="header">
          <div className="left">
            <div
              className="button"
              onClick={() => {
                localStorage.removeItem("accessToken");
                localStorage.removeItem("refreshToken");
                localStorage.removeItem("expiresAt");
                router.replace("/");
              }}
            >
              <Image src="/back.svg" alt="back" width={40} height={40} />
            </div>
          </div>
          <div className="center">
            <div className="title">Spotify Helper</div>
          </div>
        </div>
        <div className={styles.body}>
          {playlists?.map((playlist) => (
            <Playlist playlist={playlist} key={playlist.id} />
          ))}
        </div>
      </div>
    </>
  );
}
